notifications draft
status-im/specs pull request #104
Opened 2020-04-29 11:51 UTC by yenda

2020-04-29 12:18 UTC, decanus requested changes

2020-04-29 12:18 UTC, decanus commented on docs/draft/notifications.md
> +Android allows running services on the device. When the user enables notifications, the client starts a ``Foreground Service`, and a permanent notification indicating that the service is running is d
```suggestion
Android allows running services on the device. When the user enables notifications, the client starts a `Foreground Service`, and a permanent notification indicating that the service is running is displayed to the user, as required by Android guidelines.
```

2020-05-06 06:48 UTC, oskarth requested changes
Good start! I left some comments in-line. The main thing is shifting mindset from thinking "current app" to "how would a new client implement Status notifications? This has implications for language (MUST, SHOULD, etc) what we include and don't (future development, historical accidents)

2020-05-06 06:48 UTC, oskarth commented on docs/draft/notifications.md
> +permalink: /specs/draft
Add number to spec and PR title; make sure it doesn't conflict with existing PRs

2020-05-06 06:48 UTC, oskarth commented on docs/draft/notifications.md
> +## Why is there no Push Notifications?
It'd be better to start by describing how notifications work (to the extent that they do). Then we can have this as an FAQ/motivation for now doing X.

I'd also cut some of the "earlier implementations..." as it isn't useful in a spec. If we want to keep this, it should be in a later section, like FAQ etc.

2020-05-06 06:48 UTC, oskarth commented on docs/draft/notifications.md
> +## Local Notifications
This is a better start. I'd start by describing requirements and design goals. Then lead to how we solve it with local notifications for Android, and write about limitation for iOS.

2020-05-06 06:48 UTC, oskarth commented on docs/draft/notifications.md
> +Android allows running services on the device. When the user enables notifications, the client starts a `Foreground Service`, and a permanent notification indicating that the service is running is di
This currently reads more like "the (one) client does this". Ideally it should read something like: "If a client wants to support notifications, it MUST do X, Y, Z etc.

Then less emphasis on specific implementation details, other than what is relevant for all implementations (e.g. Nim based, greenfield, other Go impl, desktop one, etc etc)

2020-05-06 06:48 UTC, oskarth commented on docs/draft/notifications.md
> +## Future development
I'd de-emphasize this as it isn't the core part of a spec. If we want to include it I'd instead refer to an issue where future development is tracked.

2020-05-07 11:22 UTC, oskarth commented on docs/draft/notifications.md
> +Since iOS cannot reliably display local notifications, we need to find an alternative. But we should not impact Android users with iOS limitations.
## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

2020-05-14 04:55 UTC, oskarth commented
Ping @yenda

2020-05-14 10:23 UTC, decanus requested changes

2020-05-14 10:23 UTC, decanus commented on docs/draft/notifications.md
> +In the Android client, events from `status-go` are handled by the `handleSignal` method of `im.status.ethereum.module`. Those signals are passed to the clojurescript part of the client. This is the g
```suggestion
In the Android client, events from `status-go` are handled by the `handleSignal` method of `im.status.ethereum.module`. Those signals are passed to the clojurescript part of the client. This is the general behavior when the client is in the foreground. For the local notifications, we also react to these signals when the app is in the background. Currently, we only display a notification for 1-1 messages, but support for any signal that status-go may send can be easily added.
```

2020-05-25 05:18 UTC, oskarth commented
Ping @yenda whats the state of this? It'd be great if we can merge it and create follow up issues where things still need to be done.

2020-06-02 10:01 UTC, oskarth commented
Seems like some of the earlier outstanding comments are still unresolved? @yenda

2020-06-10 09:12 UTC, oskarth approved these changes

2020-06-15 09:05 UTC, yenda commented
@andremedeiros @decanus is this all good for you?

2020-06-15 12:24 UTC, andremedeiros approved these changes

2020-06-15 12:29 UTC, decanus approved these changes

2020-06-15 12:40 UTC, merged