Update secure transport
status-im/specs pull request #50
Opened 2019-09-10 11:32 UTC by cammellos

Update secure transport docs, remove non-implemented features.

2019-09-10 15:15 UTC, adambabik commented on status-account-spec.md
> +- a bundle SHOULD be distributed on the contact code channel. This is the whisper topic `{IK}-contact-code`, where `IK` is the hex encoded public key of the user. The channel is encrypted in the same
Hex encoded with `0x` as a prefix or without?

2019-09-10 15:39 UTC, cammellos commented on status-account-spec.md
> +- a bundle SHOULD be distributed on the contact code channel. This is the whisper topic `{IK}-contact-code`, where `IK` is the hex encoded public key of the user. The channel is encrypted in the same
good point , prefixed with `0x` , updated specs

2019-09-11 16:47 UTC, corpetty requested changes
minor changes, nitpicky but might as well get them done. Great updates.

2019-09-11 16:47 UTC, corpetty commented on status-secure-transport-spec.md
> +Prekey bundles are can be extracted from any user's messages, or found via searching for their specific topic, `{IK}-contact-code`.
`are can be` should be changed for proper grammar.

2019-09-11 16:47 UTC, corpetty commented on status-session-management-spec.md
> +If two sessions are created concurrently between two peers the one with the symmetric key, first in byte order SHOULD be used this marks that the other has expired.
no `,` needed

2019-09-11 16:47 UTC, corpetty commented on status-session-management-spec.md
> +If two sessions are created concurrently between two peers the one with the symmetric key, first in byte order SHOULD be used this marks that the other has expired.
add a `,` after `SHOULD be used`

2019-09-12 06:33 UTC, cammellos commented
@adambabik @corpetty ready to be reviewed again, thanks!

2019-09-12 12:59 UTC, corpetty approved these changes

2019-09-12 12:59 UTC, merged